### ISSUE TITLE
Composting Items Not Functioning

### ISSUE THREAD

**Issue by WenXin20** [Soupbubbles/Vanilla-Boom#2]
`Minecraft v1.14.4`
`Forge v28.1.111`
`Vanilla Boom v1.6.3.0`

I found an error in the logs that said that it could not add the pinecone to the compost bin. The error starts at `[11:16:46]` with 
`[modloading-worker-1/ERROR]: Could not add minecraftboom:pinecone to registerCompostable`.
[Log](url)

**Comment by pokmon987** [comment]
Log doesn't show up

**Comment by WenXin20** [comment]
The link probably expired, here's a new one:
https://gist.github.com/WenXin20/bcfc88947786e161509d59af69e3f49b

**Comment by Soupbubbles** [comment]
This should be fixed now! Please post again if this issue remains
