### ISSUE TITLE
Painting's cause the server to crash

### ISSUE THREAD

**Issue by drakosoldier298** [Soupbubbles/Vanilla-Boom#4]
Anytime we place any painting from this mod Our entire server crashes.

**Comment by Soupbubbles** [comment]
Will take a look at this! What version are you using?

**Comment by Soupbubbles** [comment]
And could you include a crash report

**Comment by drakosoldier298** [comment]
[crash-2020-07-24_20.44.56-server.txt](https://github.com/Soupbubbles/Vanilla-Boom/files/4977753/crash-2020-07-24_20.44.56-server.txt)

version 1.16.1-1.6.6.1

**Comment by Soupbubbles** [comment]
I have uploaded a new file, hopefully this will fix the error, report back if there is any trouble!
